apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
  namespace: skala-practice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
        - name: my-flask-app
          image: amdp-registry.skala-ai.com/skala25a/my-flask-app:latest
          ports:
            - containerPort: 5000
